[package]
name = "live"
version = "0.1.0"
authors = ["Gleb Chashchukhin <gleb.chashchuhin@konsec.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = ""
termion = "1.5.5"

